# GitHub Pages overrides
#safe: true
#source: <your pages repo>
#destination: <the build dir>
#lsi: false
#pygments: true

# our settings
timezone: America/Edmonton
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'fenced_code_blocks', 'autolink', 'disable_indented_code_blocks', 'strikethrough', 'underline', 'highlight', 'footnotes']
permalink: /blog/:year/:month/:title
paginate: 8
paginate_path: /blog/page/:num
excerpt_separator: <!--more-->
# custom globals (variables)
blog:
  title: Victor's Blog
  tagline: articulation, assertions, calls, exclamations, voice, words
  author:
    name: Victor
    url: http://victorz.ca
  url: http://vwww.github.io/www/blog
  short_url: victorz.ca/blog
3d:
  location: /misc/3d/
  areas:
    base:
      name: Homepage
      pages:
        base: Home!
    advanced:
      name: Advanced revit architecture.rvt
      pages:
        base: Overview
        balcony: Balcony View
        courtyard: Building Courtyard
        floor: 03 - Floor Public - Day Rendering
        fly: Fly into Building
        park: From Parking Area
    basic:
      name: Basic revit architecture.rvt
      pages:
        base: Overview
        aerial: Aerial
        fireplace: Fireplace
        ground: Ground Approach
        kitchen: Kitchen
        sectional: Sectional Persp(ective)
    coffee:
      name: Coffee maker.dwg
      pages:
        base: Overview
        0: 0 deg cam
        30: 30 deg cam
        60: 60 deg cam
        90: 90 deg cam
        120: 120 deg cam
        150: 150 deg cam
        180: 180 deg cam
        210: 210 deg cam
        240: 240 deg cam
        270: 270 deg cam
        300: 300 deg cam
        cam1: Camera1
        cam2: Camera2
    diaphanous:
      name: Diaphanous house.dwg
      pages:
        base: Overview
        east: EXT East
        ne: EXT NE_Low
        living: Living Room
        lvng_1700: LVNG_1700
        stairs: STAIRS01
  environments:
    none:
      name: None
      desc: No environment applied.
    field:
      name: Field
      desc: A field on a farm.
    crossroads:
      name: Crossroads
      desc: A 4-way intersection.
    boardwalk:
      name: Boardwalk
      desc: A bridge on the dock.
    riverbank:
      name: Riverbank
      desc: A pond near a river.
    seaport:
      name: Seaport
      desc: An estate near the sea.
gg:
  pages:
    index:
      title: Home
#    rps:
#      title: Rock Paper Scissors
#      game_desc: Rocks smash scissors, which cut paper, which covers the first. This game is not limited to two players; this version supports <b>unlimited players</b>.
#      subpages:
#        help: Instructions
#    morra:
#      title: Morra
#      game_desc: Choose a number, which will be part of a total, and then guess if the sum will be odd or even. This game supports <b>unlimited players</b>.
#      subpages:
#        help: Instructions
#    blackjack:
#      title: Blackjack
#      game_desc: Also known as 21, this game is popular in casinos. Using virtual credits, play it here without risking your money. This game supports <b>unlimited players</b> but requires <b>waiting</b> between rounds.
#      subpages:
#        help: Instructions
#    cheat:
#      title: Cheat
#      game_desc: This is a shedding-type card game whose rules allow cheating! However, making a false accusation or being caught cheating results in receiving the entire deck. This game supports <b>unlimited players</b> but late players have a <b>disadvantage</b>.
#      subpages:
#        help: Instructions
    uttt:
      title: Ultimate Tic-Tac-Toe
      game_desc: This is Tic-Tac-Toe (noughts and crosses) squared! It's more complicated than regular Tic-Tac-Toe, in which experts can always force a tie. This game requires <b>match-making</b>, so ask a friend to join you.
      subpages:
        help: Instructions
    about:
      title: About
